language: node_js
node_js:
  - "node"
before_script:
  - npm install -g acorn
script:
- acorn --silent firefox/user.js
- acorn --silent fennec/user.js
- acorn --silent thunderbird/user.js
- acorn --silent waterfox/user.js
- acorn --silent palemoon/user.js