sudo: false
language: node_js
node_js:
  - "node"
before_script:
  - npm install -g acorn
script:
- acorn firefox/user.js
- acorn fennec/user.js
- acorn thunderbird/user.js
- acorn waterfox/user.js
- acorn palemoon/user.js
